[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "gcc"]

[phases.install]
cmds = [
    "python -m venv --copies --upgrade-deps /opt/venv", # Create/ensure venv, upgrade pip/setuptools within it
    ". /opt/venv/bin/activate && pip install --no-cache-dir -r requirements.txt"
]
