[phases.install]
# --no-cache-dir.
cmds = [
    "pip install --no-cache-dir --upgrade pip setuptools",
    "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install --no-cache-dir -r requirements.txt"
]
